//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScrumDevelopmentServices
{
    using System;
    using System.Collections.Generic;
    
    public partial class AcceptanceTest
    {
        public int id { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public int userStoryId { get; set; }
    
        public virtual UserStory UserStory { get; set; }
    }
}
