//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScrumDevelopmentServices
{
    using System;
    using System.Collections.Generic;
    
    public partial class Project
    {
        public Project()
        {
            this.ProjectUsers = new HashSet<ProjectUser>();
            this.Sprints = new HashSet<Sprint>();
            this.UserStories = new HashSet<UserStory>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public string startDate { get; set; }
    
        public virtual ICollection<ProjectUser> ProjectUsers { get; set; }
        public virtual ICollection<Sprint> Sprints { get; set; }
        public virtual ICollection<UserStory> UserStories { get; set; }
    }
}
