//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScrumDevelopmentServices
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sprint
    {
        public Sprint()
        {
            this.SprintUsers = new HashSet<SprintUser>();
            this.UserStories = new HashSet<UserStory>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string StartDate { get; set; }
        public string EndDate { get; set; }
        public Nullable<int> ProjectId { get; set; }
    
        public virtual Project Project { get; set; }
        public virtual ICollection<SprintUser> SprintUsers { get; set; }
        public virtual ICollection<UserStory> UserStories { get; set; }
    }
}
