//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScrumDevelopmentServices
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task
    {
        public int Id { get; set; }
        public Nullable<int> userStoryId { get; set; }
        public string userEmail { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<bool> Blocked { get; set; }
        public string Reason { get; set; }
        public Nullable<int> Hours { get; set; }
    
        public virtual User User { get; set; }
        public virtual UserStory UserStory { get; set; }
    }
}
