//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScrumDevelopmentServices
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserStory
    {
        public UserStory()
        {
            this.AcceptanceTests = new HashSet<AcceptanceTest>();
            this.Tasks = new HashSet<Task>();
        }
    
        public int Id { get; set; }
        public Nullable<int> sBacklogId { get; set; }
        public string title { get; set; }
        public string Description { get; set; }
        public int storyPoints { get; set; }
        public int priority { get; set; }
        public Nullable<int> projectId { get; set; }
        public Nullable<int> sprintId { get; set; }
    
        public virtual ICollection<AcceptanceTest> AcceptanceTests { get; set; }
        public virtual Project Project { get; set; }
        public virtual Sprint Sprint { get; set; }
        public virtual SprintBacklog SprintBacklog { get; set; }
        public virtual ICollection<Task> Tasks { get; set; }
    }
}
