//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScrumDevelopmentServices
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.ProjectUsers = new HashSet<ProjectUser>();
            this.Tasks = new HashSet<Task>();
        }
    
        public string email { get; set; }
        public string name { get; set; }
        public string password { get; set; }
        public Nullable<bool> productOwner { get; set; }
        public Nullable<bool> scrumMaster { get; set; }
        public Nullable<bool> developer { get; set; }
        public string bio { get; set; }
    
        public virtual ICollection<ProjectUser> ProjectUsers { get; set; }
        public virtual ICollection<Task> Tasks { get; set; }
    }
}
